### ISSUE TITLE
Theme Cleanup Plan

### ISSUE THREAD

**Issue by fofajardo** [FranklinDM/Moonscape#1]
Here are the current plans on the theme at the time being.

There are still a lot of things to do such as:
- [x] Update the install manifest
- [x] Update the readme and internal documentation
- [x] Global rename (fxscape-mscape)
- [x] Update and add additional images
- [x] Fix remaining bugs and references to Firefox
- [x] Improve appearance of blurry resized images
- [x] Removed all unused files

**Comment by FranklinDM** [comment]
Results for the past few months:
Fix duplicate learn more link inherited from FF - #7 
Add an icon pack for Linux - #6 
Support PM's padlock - #4 
Add implementation of PM's padlock - #2
